name: Daily Task

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜（UTC时间）

jobs:
  daily-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run some task
        run: |
          echo "This task runs daily at midnight UTC"
